spring:
  datasource:
    url: jdbc:h2:mem:purchasedb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    # Disable hibernate auto schema creation
    hibernate:
      ddl-auto: none
  h2:
    console.enabled: true
  # Makes console log output colourful
  output:
    ansi:
      enabled: ALWAYS
  lifecycle:
    timeout-per-shutdown-phase: 20s

server:
  port: 8082
  servlet:
    context-path: "/purchasing-service"
  shutdown: graceful

services:
  product-service:
    url: http://localhost:8081/product-service
