spring:
  application:
    name: Purchasing-Service
  datasource:
    url: jdbc:h2:mem:purchasedb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # Disable hibernate auto schema creation
    hibernate:
      ddl-auto: none
  h2:
    console.enabled: true
  # Makes console log output colourful
  output:
    ansi:
      enabled: ALWAYS
  lifecycle:
    timeout-per-shutdown-phase: 20s
  threads:
    virtual:
      enabled: true

server:
  port: 8082
  servlet:
    context-path: "/purchasing-service"
  shutdown: graceful

services:
  product-service:
    url: http://localhost:8081/product-service
  order-service:
    url: http://localhost:8083/order-service

gsshop-common:
  auth:
    enabled: true
    jwt-token-secret: c63714bee7677d179d980aeceffb1a2ac63ebb25933cc16ad58d90f043b9da9f1c22b6d70e7ec8183884108eb6660be5d1cfba7da55b56cfa6e8ba201f97370a
    jwt-token-salt: abcd1234
    security-ignore-urls: /purchase/**,/orders/**
    jwt-token-validity: 3600000